"""empty message

Revision ID: 7594da09cdda
Revises: 
Create Date: 2022-04-03 17:06:45.232965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7594da09cdda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('idrol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('idrol')
    )
    op.create_table('usuario',
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=40), nullable=True),
    sa.Column('nombres', sa.String(length=60), nullable=True),
    sa.Column('apellidos', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('clave', sa.String(length=255), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.idrol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idusuario'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('rol')
    # ### end Alembic commands ###
